name: Regression Build

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  build:
    env:
      ISHEADLESS: true
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Regression suite
        run: mvn -Dtest=RegressionSuite test
        
        
