name: Regression Build

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Regression suite
        run: mvn -Dtest=RegressionSuite test